"""empty message

Revision ID: 0d66c1f2e570
Revises: 1ba004b1f441
Create Date: 2024-12-29 19:34:34.098807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d66c1f2e570'
down_revision = '1ba004b1f441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('engineers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('engineers', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
