"""empty message

Revision ID: 258e5626f68b
Revises: 3531bbddf963
Create Date: 2025-01-05 10:36:29.160480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258e5626f68b'
down_revision = '3531bbddf963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
