"""empty message

Revision ID: 5855443120f9
Revises: f73fbefcf85b
Create Date: 2024-12-24 13:40:53.475248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5855443120f9'
down_revision = 'f73fbefcf85b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ingenieros',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('ingenieros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingenieros_provider_id'), ['provider_id'], unique=False)

    op.create_table('sucursales',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sucursales_client_id'), ['client_id'], unique=False)

    op.create_table('tickets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=False),
    sa.Column('engineer_id', sa.BigInteger(), nullable=False),
    sa.Column('branch_id', sa.BigInteger(), nullable=False),
    sa.Column('activity', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('return_process', sa.Boolean(), nullable=True),
    sa.Column('billing_status', sa.String(length=20), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['engineer_id'], ['ingenieros.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_engineer_id'), ['engineer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_provider_id'), ['provider_id'], unique=False)

    op.create_table('bitacora_tickets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bitacora_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bitacora_tickets_ticket_id'), ['ticket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bitacora_tickets_user_id'), ['user_id'], unique=False)

    op.create_table('facturacion',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facturacion_ticket_id'), ['ticket_id'], unique=False)

    op.drop_table('items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    with op.batch_alter_table('facturacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facturacion_ticket_id'))

    op.drop_table('facturacion')
    with op.batch_alter_table('bitacora_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bitacora_tickets_user_id'))
        batch_op.drop_index(batch_op.f('ix_bitacora_tickets_ticket_id'))

    op.drop_table('bitacora_tickets')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_provider_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_engineer_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_client_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_branch_id'))

    op.drop_table('tickets')
    with op.batch_alter_table('sucursales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sucursales_client_id'))

    op.drop_table('sucursales')
    with op.batch_alter_table('ingenieros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingenieros_provider_id'))

    op.drop_table('ingenieros')
    op.drop_table('usuarios')
    op.drop_table('proveedores')
    op.drop_table('clientes')
    # ### end Alembic commands ###
